name: GitHub Actions Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{secrets.REMOTE_IP}}
          username: ${{secrets.NCP_ID}}
          passwrod: ${{secrets.NCP_PW}}
          port: ${{secrets.REMOTE_SSH_PORT}}
          script: |
            whoami
            ls -al
            
        
