name: GitHub Actions Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 최신 버전을 다운로드 받습니다.
        uses: actions/checkout@v4.1.1

      - name: 환경 변수를 설정합니다.
        run: |
          echo "NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL" >> .env
          echo "HTTPS=$HTTPS" >> .env
        env:
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          HTTPS: ${{ secrets.HTTPS }}

      - name: 도커 이미지를 생성하고 도커 허브에 업로드합니다.
        run: |
          docker login -u $DOCKER_ID -p $DOCKER_PW
          docker build -t $DOCKER_REPO:latest ./
          docker push $DOCKER_REPO:latest
        env:
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          DOCKER_PW: ${{ secrets.DOCKER_PW }}
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}        
        
